# Generated by Django 2.2.1 on 2019-08-18 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file_uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSaveFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploadedfile', models.FileField(upload_to=file_uploads.models.user_dir_path, validators=[file_uploads.models.CareerSaveFileModel.validate_size], verbose_name='FIFA 19 Career File')),
                ('fifa_edition', models.IntegerField(blank=True, default=19, null=True)),
                ('file_process_status_code', models.IntegerField(blank=True, default=0, null=True)),
                ('file_process_status_msg', models.CharField(blank=True, max_length=120, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
