# Generated by Django 2.2.1 on 2019-08-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersavefilemodel',
            name='position_in_queue',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
