# Generated by Django 2.2.1 on 2019-08-27 10:34

from django.db import migrations, models
import file_uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0002_careersavefilemodel_position_in_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersavefilemodel',
            name='ing_date',
            field=models.CharField(blank=True, default='20080101', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='careersavefilemodel',
            name='save_original_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='careersavefilemodel',
            name='save_type',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='careersavefilemodel',
            name='teamid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='careersavefilemodel',
            name='uploadedfile',
            field=models.FileField(upload_to=file_uploads.models.user_dir_path, validators=[file_uploads.models.CareerSaveFileModel.validate_size], verbose_name='FIFA Career File'),
        ),
    ]
