# Generated by Django 2.2.1 on 2019-08-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0003_auto_20190827_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersavefilemodel',
            name='ft_slot',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
