# Generated by Django 2.2.1 on 2019-09-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0004_careersavefilemodel_ft_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersavefilemodel',
            name='is_update',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
