# Generated by Django 2.0 on 2018-03-13 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('currency', models.CharField(choices=[(0, 'USD'), (1, 'Euro'), (2, 'Pound')], default=1, max_length=1)),
                ('unit_system', models.BooleanField(default=0)),
                ('is_public', models.BooleanField(default=1)),
            ],
        ),
    ]
