# Generated by Django 2.0 on 2018-06-04 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180604_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now),
        ),
    ]
