# Generated by Django 2.0 on 2018-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180604_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.CharField(blank=True, default='2008-06-04 16:46:22.179423', max_length=34, null=True),
        ),
    ]
