# Generated by Django 2.2.1 on 2019-05-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datausersplayers',
            name='commonname',
        ),
        migrations.RemoveField(
            model_name='datausersplayers',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='datausersplayers',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='datausersplayers',
            name='playerjerseyname',
        ),
        migrations.RemoveField(
            model_name='datausersplayers17',
            name='commonname',
        ),
        migrations.RemoveField(
            model_name='datausersplayers17',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='datausersplayers17',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='datausersplayers17',
            name='playerjerseyname',
        ),
        migrations.RemoveField(
            model_name='datausersplayers19',
            name='commonname',
        ),
        migrations.RemoveField(
            model_name='datausersplayers19',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='datausersplayers19',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='datausersplayers19',
            name='playerjerseyname',
        ),
        migrations.AddField(
            model_name='datausersplayers',
            name='commonnameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datausersplayers',
            name='firstnameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datausersplayers',
            name='lastnameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datausersplayers',
            name='playerjerseynameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datausersplayers17',
            name='commonnameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datausersplayers17',
            name='firstnameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datausersplayers17',
            name='lastnameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datausersplayers17',
            name='playerjerseynameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datausersplayers19',
            name='commonnameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datausersplayers19',
            name='firstnameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datausersplayers19',
            name='lastnameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datausersplayers19',
            name='playerjerseynameid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
